name: pyright
on: [push, pull_request]

jobs:
  setup_env:
    name: pyright
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/ECY_exe

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: npm install
        run: |
          npm install -g pkg
          npm install pyright -prefix ./
          cd ./node_modules/pyright
          npm install
          ls
          pkg package.json -o ./pyright_${{ runner.os }}.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./nodejs_${{ runner.os }}.exe
