name: ECY
on: [push, pull_request]

jobs:
  setup_env:
    name: Build with pyinstaller
    strategy:
      matrix:
        neovim: [false, true]
    runs-on: windows-latest
    steps:
      #############
      #  clone  #
      #############
      - name: Checkout myself
        uses: actions/checkout@v2
        with:
          repository: JimmyHuang454/ECY_exe
          path: ECY

      ####################
      #  Install python  #
      ####################
      - name: Install Python
        uses: actions/setup-python@v1

      #########################
      #  Install pyinstaller  #
      #########################
      - name: Install pyinstaller
        run: |
          pip3 install pyinstaller
          pip3 install requests

      ###########
      #  Build  #
      ###########
      - name: Build with pyinstaller
        run: |
          cd ./ECY
          pyinstaller -F ./cli.py

      ################
      #  UploadFile  #
      ################
      - name: UploadFile
        run: python ./ECY/upload_to_release_page.py
